version: '3'
services:
  bg-mongo:
    image: mongo
    ports:
      - 27017:27017

  bg-redis:
    image: redis
    ports:
      - 6379:6379

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - bg-mongo
      - bg-redis
